project_id = "aarwezrqsvdqffoomejl"

[functions.create-test-users]
verify_jwt = false

[functions.create-employee]
verify_jwt = true

[functions.authenticate-employee]
verify_jwt = false

[functions.change-password]
verify_jwt = true
