// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aarwezrqsvdqffoomejl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcndlenJxc3ZkcWZmb29tZWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MzQ4NTYsImV4cCI6MjA3NzMxMDg1Nn0.R7kw7C2CwH_EJXWE1VLxkghcu__IUScC_24WWV4TLKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});